In [2]:
import numpy as np

In [3]:
np1 = np.arange(1,11)

print(np1 + 1)
print(np1 * 2)
print(np1 - 3)
print(np1 / 4)

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  4  6  8 10 12 14 16 18 20]
[-2 -1  0  1  2  3  4  5  6  7]
[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5 ]


In [4]:
np2 = list(range(1,11))

np3 = []
for i in np2:
    print(i*2)
    np3.append(i)

2
4
6
8
10
12
14
16
18
20


In [5]:
np4 = [[1,2,3],
       [4,5,6],
       [7,8,9]]

print("f T: {np4.shape}")


f T: {np4.shape}


In [6]:
print(f"{np4}")

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
np5 = [[1,2,3],
       [4,5,6],
       [7,8,9]]

print(np5)
print(f"reshape np: (6,1),{np5.reshape(6,1)}")

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
op2 = f'np5 flatten: {np5.flatten()}'
print(op2)
op3 = f'np3 flatten: {np5.ravel()}'
print(op3)